- .github/pull_request_template.md
Its a pr template so that we can have a reference to the Jira entry. This is something from my work group. Havent tested it yet because it needs to be merged of course... Will see if I am missing anything.
> BBC-21: Added PR template.

- api/src/main/java/com/beanbank/api/controller/AccountController.java
- api/src/main/java/com/beanbank/api/model/Account.java
- api/src/main/java/com/beanbank/api/model/User.java
- api/src/main/java/com/beanbank/api/repository/AccountRepository.java
- api/src/main/java/com/beanbank/api/service/AccountService.java
- api/src/main/java/com/beanbank/api/service/UserService.java
- api/src/main/resources/application.properties
- Added the table Account in the Java Spring
> BBC-18: Create Account Table in Java Spring

- api/src/main/java/com/beanbank/api/controller/TransactionsTypeController.java
- api/src/main/java/com/beanbank/api/model/TransactionsType.java
- api/src/main/java/com/beanbank/api/repository/TransactionsTypeRepository.java
- api/src/main/java/com/beanbank/api/service/TransactionTypeService.java
- Added the controller, service, repository, and model for `TransactionsType`
> BBC-17: Added TransactionTypes in Java

- api/src/main/java/com/beanbank/api/controller/AccountController.java
- api/src/main/java/com/beanbank/api/controller/UserController.java
- api/src/main/java/com/beanbank/api/service/AccountService.java
- api/src/main/java/com/beanbank/api/service/UserService.java
- Removed the usage of the `@Autowired` annotation as this is something that IntelliJ didn;t reccomend.
> bcc-22: Remove all usage of Autowired

- postman/Account/Account Collection.postman_collection.json
- postman/Readme.md
- postman/TransactionsType/TransactionsType.postman_collection.json
- postman/User/Users.postman_collection.json
- With this, we will all be able to test that our api calls are working correctly locally. 
- Read the `Readme.md` for further direction
> BCC-23: Add Postman collections

- schema/schema.sql
> Added database schema

- api/src/main/resources/application.properties
Update spring application data source url
> Updated spring properties file

- api/src/main/java/com/beanbank/api/controller/TransactionController.java
- api/src/main/java/com/beanbank/api/model/Transaction.java
- api/src/main/java/com/beanbank/api/repository/TransactionRepository.java
- api/src/main/java/com/beanbank/api/service/TransactionService.java
- postman/Transaction/Transaction.json
> Added Transactions entity

- .gitignore
- .idea/.gitignore
- Readme.md
- api/src/main/resources/application.properties
> run server instructions

- Readme.md
- conf/flyway.conf
- conf/flyway.toml
> clean up flyway code

- sql/V202403112144__InsertDataIntoTables.sql
- Dummy data inserted into all the tables via one single script. Tested and no errors occurred.
> Insert table data script added

- api/src/main/java/com/beanbank/api/model/BeanType.java
- api/src/main/java/com/beanbank/api/model/User.java
- Basically replicated the unique constraint in java.
> bbc-33: Add duplicate checks in api layer.

- api/src/main/java/com/beanbank/api/controller/TransactionController.java
- api/src/main/java/com/beanbank/api/repository/TransactionRepository.java
- api/src/main/java/com/beanbank/api/service/TransactionService.java
- postman/Transaction/Transaction.json
- Now the user will be able to get their transactional history
> bbc-32: added transactional history

- api/src/main/java/com/beanbank/api/model/BeanType.java
- api/src/main/java/com/beanbank/api/service/TransactionService.java
Fix api datatype for a column in BeanType table.
> Fixed BeanType model datatypes

- app/api/src/main/java/com/beanbank/api/controller/AccountController.java
- app/api/src/main/java/com/beanbank/api/controller/BeanTypeController.java
- app/api/src/main/java/com/beanbank/api/controller/TransactionController.java
- app/api/src/main/java/com/beanbank/api/controller/TransactionsTypeController.java
- app/api/src/main/java/com/beanbank/api/controller/UserController.java
- app/api/src/main/java/com/beanbank/api/repository/TransactionRepository.java
- app/api/src/main/java/com/beanbank/api/repository/TransactionsTypeRepository.java
- app/api/src/main/java/com/beanbank/api/service/AccountService.java
- app/api/src/main/java/com/beanbank/api/service/BeanTypeService.java
- app/api/src/main/java/com/beanbank/api/service/TransactionService.java
- app/api/src/main/java/com/beanbank/api/service/TransactionTypeService.java
- app/api/src/main/java/com/beanbank/api/service/UserService.java
- app/cli/pom.xml
- app/cli/src/main/java/Main.java
- app/cli/src/main/java/request/Request.java
- app/cli/src/main/java/request/RequestType.java
- app/cli/src/main/java/request/UserRequest.java
- app/cli/src/main/java/session/Session.java
- app/cli/src/main/java/session/SessionManager.java
- app/shared/src/main/java/com/models/BeanType.java
- app/shared/src/main/java/com/models/Transaction.java
- app/shared/src/main/java/com/models/User.java
Added Users logging in feature
> Added Users logging in feature

- .github/workflows/releases.yml
- .gitignore
- Readme.md
- app/api/pom.xml
- app/cli/pom.xml
- app/pom.xml
- app/shared/pom.xml
- Automatically creates release packages
> Create release workflow [DON'T MERGE]

- .github/workflows/deploy-server.yml
- app/api/src/main/resources/application.properties
> Hide db pass

- app/api/src/main/resources/application.properties
- app/cli/src/main/java/request/Request.java
- app/cli/src/main/java/request/UserRequest.java
- app/cli/src/main/java/session/Session.java
- app/cli/src/main/java/session/SessionManager.java
- app/cli/src/main/java/util/UserInputHandler.java
- Users can login and create accounts
> Added login and registration

- app/api/src/main/java/com/beanbank/api/controller/AccountController.java
- app/api/src/main/java/com/beanbank/api/repository/AccountRepository.java
- app/api/src/main/java/com/beanbank/api/service/AccountService.java
- Added endpoint to get all accounts for a user
> Added get accounts for userID endpoint

- app/cli/src/main/java/session/Session.java
- app/cli/src/main/java/session/SessionManager.java
Here is a list of all available commands:
----------------------------------------
-logout
-help
-dashboard
-createAccount
-closeAccount
-deposit
-withdraw
-help
-exit
-transfer
> create command list

- app/cli/src/main/java/request/UserRequest.java
- app/cli/src/main/java/session/Session.java
- app/cli/src/main/java/session/SessionManager.java
- app/cli/src/main/java/util/UserInputHandler.java
Added password hiding and repeated prompting for duplicate entries
> Added password hiding and repeated prompting for duplicate entries

- app/cli/pom.xml
- app/cli/src/main/java/session/Session.java
> Added hashing of passwords

- postman/User/Users.postman_collection.json
> BCC-49: Integration tests for User

- postman/TransactionsType/TransactionsType.postman_collection.json
> BCC-47: Integration tests for Transaction Types

- app/shared/src/main/java/com/models/Account.java
- app/shared/src/main/java/com/models/BeanType.java
- app/shared/src/main/java/com/models/Transaction.java
- app/shared/src/main/java/com/models/TransactionsType.java
> BBC-58: Add constructors to models

- app/api/src/main/java/com/beanbank/api/controller/UserController.java
- app/api/src/main/java/com/beanbank/api/repository/UserRepository.java
- app/api/src/main/java/com/beanbank/api/service/UserService.java
- app/cli/src/main/java/request/UserRequest.java
- app/cli/src/main/java/session/Session.java
- postman/User/Users.postman_collection.json
Search for a user by their username or email
> Added search for user by either username or email

- app/api/src/test/java/com/beanbank/api/serviceTests/TransactionsTypeServiceTests.java
> BBC-56: unit tests for transactions-type

- app/api/src/test/java/com/beanbank/api/serviceTests/BeanTypeServiceTests.java
> BBC-57: Added unit tests for BeanType.
